[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path  = "cache"

[rpc_endpoints]
base_mainnet = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api", chain = 8453 }
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api", chain = 84532 }
